language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install pylint
script:
  - pylint --rcfile=.pylintrc infaketure
  - PYTHONPATH=$PWD python test/test_infaketure.py
