language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update -qq
install:
  - pip install pep8 --use-mirrors
script:
  - cd $PWD/src; pep8 --max-line-length=120 --ignore=E402 --show-source infaketure && echo 'PEP8 is clean'
  - PYTHONPATH=$PWD python $PWD/test/testsuite.py
