language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
before_install:
  - sudo apt-get update -qq
install:
  - pip install pep8 --use-mirrors
env:
  - SRC_DIR=$PWD/src
  - TEST_DIR=$SRC_DIR/test
  - PYTHONPATH=$PYTHONPATH:$PWD:$SRC_DIR
script:
  - "cd $SRC_DIR; pep8 --max-line-length=120 --ignore=E402 --show-source infaketure && echo 'PEP8 is clean'"
  - "python $TEST_DIR/test_infaketure.py"
